Dependency Injection
andrewcchau/TwitterMultiApp pull request #12
Opened 2018-07-12 22:24 UTC by andrewcchau

Refactored project to use dependency injection

2018-07-12 22:31 UTC, kev-chan requested changes
create a Provider for Twitter

2018-07-12 22:31 UTC, kev-chan commented on src/main/java/lithium/university/services/TwitterService.java
> +@Module
you should not need @Module on TwitterService

2018-07-12 22:31 UTC, kev-chan commented on src/main/java/lithium/university/services/TwitterService.java
> +    public TwitterService provideTwitterService() { return new TwitterService(); }
this should not be needed

2018-07-12 22:31 UTC, kev-chan commented on src/main/java/lithium/university/TwitterApplication.java
> +    interface TwitterSetUp {
let's move it to a separate class

2018-07-13 21:27 UTC, kev-chan requested changes

2018-07-13 21:27 UTC, kev-chan commented on src/main/java/lithium/university/TwitterProvider.java
> +public class TwitterProvider implements Provider {
this class can be simplified
do you need to implement Provider and use the @Provides annotation?

2018-07-13 21:27 UTC, kev-chan commented on src/main/java/lithium/university/services/TwitterService.java
> +    @Inject public TwitterService() {}
do you actually need @Inject?

2018-07-13 21:29 UTC, andrewcchau commented on src/main/java/lithium/university/services/TwitterService.java
> +    @Inject public TwitterService() {}
You'll get a compilation error "Dagger/MissingBinding" without @Inject

2018-07-13 22:34 UTC, merged