Services and Resources
andrewcchau/TwitterMultiApp pull request #8
Opened 2018-07-02 20:52 UTC by andrewcchau

Separated resource and services files into appropriate sub-packages

2018-07-03 16:20 UTC, kev-chan requested changes

2018-07-03 16:20 UTC, kev-chan commented on src/main/java/lithium/university/services/TwitterServices.java
> +    public Status postToTwitter(Twitter twitter, String message, int tweetTotal) throws TwitterException {
i like the change.  Now what happens if someone else was to pass in a long tweet vs empty tweet?

2018-07-03 16:21 UTC, kev-chan commented on src/main/java/lithium/university/services/TwitterServices.java
> +public class TwitterServices {
TwitterService is a better name

2018-07-03 16:23 UTC, kev-chan commented on src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> +mock-maker-inline
what is this used for?

2018-07-03 17:27 UTC, andrewcchau commented on src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> +mock-maker-inline
Forgot to remove this from commit. Will take out as it's not needed with current code base

2018-07-03 19:13 UTC, kev-chan requested changes

2018-07-03 19:13 UTC, kev-chan commented on src/main/java/lithium/university/resources/TwitterResource.java
> +            if (te.getMessage().contains("length")) {
did you think about the scenario where Twitter4j itself returns back an exception with type "length"?

2018-07-05 14:42 UTC, kev-chan requested changes

2018-07-05 14:42 UTC, kev-chan commented on src/main/java/lithium/university/resources/TwitterResource.java
> +        if(message == null){
any reason why the null check is here?

2018-07-05 15:12 UTC, merged